name: Deploy na DockerHub

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Prijava v DockerHub
        run: |
          sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Gradnja Docker slike
        run: |
          sudo docker build -t $DOCKER_USERNAME/binarni_radix_sort:${{ github.sha }} .

      - name: Pushing Docker slike na DockerHub
        run: |
          sudo docker push $DOCKER_USERNAME/binarni_radix_sort:${{ github.sha }}

