name: Deploy na DockerHub

on:
  workflow_run:
    workflows: ["Testiranje Radix Sort"]
    types:
      - completed

jobs:
  build_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Prijava v DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Gradnja Docker slike
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/Binarni_Radix_Sort:${{ github.sha }} .

      - name: Pushing Docker slike na DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/Binarni_Radix_Sort:${{ github.sha }}

      - name: Potisni najnovejšo različico (latest)
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/Binarni_Radix_Sort:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/Binarni_Radix_Sort:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/Binarni_Radix_Sort:latest
