name: Deploy na DockerHub

env: #Pridobimo username in password od dockerhub repozitorija
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
on:
  workflow_run:
    workflows: ["Testiranje Radix Sort"]
    types:
      - completed

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Prijava v DockerHub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Gradnja Docker slike
        run: |
          docker build -t $DOCKER_USERNAME/binarni_radix_sort:${{ github.sha }} .

      - name: Pushing Docker slike na DockerHub
        run: |
          docker push $DOCKER_USERNAME/binarni_radix_sort:${{ github.sha }}

